"""Recover hash-identical HVP directions on the original CPU host, without CUDA.

Exports bounded ZIP parts for the existing run; it does not rerun GPU tests.
If regenerated bytes differ, stop instead of exporting a substitute direction.
"""
import argparse
from datetime import datetime
import hashlib
from io import BytesIO
import json
import os
from pathlib import Path
import subprocess
import zipfile
import numpy as np
import torch

try:
    from .author_step4_reference import inputs,tensor_hashes,inventory
except ImportError:
    from author_step4_reference import inputs,tensor_hashes,inventory

MAX_PART_BYTES=48*2**20


def export(archive,output_root):
    torch.set_num_threads(2)
    source_sha=hashlib.sha256(archive.read_bytes()).hexdigest()
    with zipfile.ZipFile(archive) as z:
        assert len(z.namelist())==len(set(z.namelist()))
        assert sum(i.file_size for i in z.infolist())<=512*2**20
        hashes=json.loads(z.read('artifact-sha256.json'))
        assert set(hashes)==set(z.namelist())-{'artifact-sha256.json'}
        assert all(hashlib.sha256(z.read(n)).hexdigest()==h for n,h in hashes.items())
        summary=json.loads(z.read('step4-summary.json'))
        assert summary['inventory']==inventory()
        helper=Path(__file__).with_name('author_step4_reference.py')
        assert hashlib.sha256(helper.read_bytes()).hexdigest()==summary['validation_code_sha256'][helper.name]
        records=[json.loads(z.read(r['id']+'/result.json')) for r in summary['runs']]
    required=[r for r in records if r.get('hvp')]
    output_root.mkdir(parents=True,exist_ok=True)
    folder=output_root/('author_flashsinkhorn_step4_directions_'+datetime.now().strftime('%Y%m%d_%H%M%S')+f'_{os.getpid()}')
    folder.mkdir(exist_ok=False)
    common={'kind':'author_step4_directions_v1','source_archive_sha256':source_sha,
        'torch':torch.__version__,'required_cases':[r['case']['id'] for r in required]}
    paths=[];members={};size=0
    def flush():
        nonlocal members,size
        if not members:return
        target=folder/f'part_{len(paths)+1:02d}.zip'
        manifest=dict(common,files={n:hashlib.sha256(b).hexdigest() for n,b in members.items()})
        with zipfile.ZipFile(target,'x',zipfile.ZIP_DEFLATED) as z:
            for n,b in members.items():z.writestr(n,b)
            z.writestr('directions-manifest.json',json.dumps(manifest,indent=2))
        paths.append(target);members={};size=0
    for i,r in enumerate(required,1):
        raw=inputs(r['case'])
        assert tensor_hashes(raw)==r['input_sha256'], f"{r['case']['id']}: original input bytes not recovered"
        buffer=BytesIO();np.save(buffer,raw[-1].numpy(),allow_pickle=False);payload=buffer.getvalue()
        assert len(payload)<=MAX_PART_BYTES
        if size+len(payload)>MAX_PART_BYTES:flush()
        members[r['case']['id']+'.npy']=payload;size+=len(payload)
        print(f"[directions] {i}/{len(required)} {r['case']['id']} hash verified",flush=True)
    flush()
    (folder/'export.json').write_text(json.dumps(dict(common,parts=[str(p) for p in paths]),indent=2)+'\n',encoding='utf-8')
    for p in paths:print(f'[directions] Artifact: {p.resolve()}',flush=True)
    return paths


def load_directions(parts,source_sha):
    """Read numeric arrays only; caller verifies each direction against original hash."""
    directions={};required=None;total=0
    for path in parts:
        with zipfile.ZipFile(path) as z:
            total+=sum(i.file_size for i in z.infolist());assert total<=256*2**20
            names=z.namelist();assert len(names)==len(set(names))
            manifest=json.loads(z.read('directions-manifest.json'))
            assert manifest['kind']=='author_step4_directions_v1' and manifest['source_archive_sha256']==source_sha
            assert set(manifest['files'])==set(names)-{'directions-manifest.json'}
            if required is None:required=manifest['required_cases']
            assert required==manifest['required_cases'] and len(required)==len(set(required))
            for name,h in manifest['files'].items():
                payload=z.read(name);assert hashlib.sha256(payload).hexdigest()==h
                assert name.endswith('.npy') and name[:-4] in required and name[:-4] not in directions
                array=np.load(BytesIO(payload),allow_pickle=False)
                assert array.dtype==np.float32 and array.ndim==2 and np.isfinite(array).all()
                directions[name[:-4]]=torch.from_numpy(array.copy())
    assert set(directions)==set(required or []), 'Missing direction supplement parts'
    return directions


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('archive',type=Path)
    p.add_argument('--output-root',type=Path,default=Path(__file__).resolve().parents[1]/'outputs')
    p.add_argument('--upload',action='store_true',help='Commit only exported ZIP parts and push origin/main')
    args=p.parse_args();parts=export(args.archive,args.output_root)
    if args.upload:
        root=Path(__file__).resolve().parents[1]
        branch=subprocess.run(['git','branch','--show-current'],cwd=root,text=True,capture_output=True,check=True).stdout.strip()
        if branch!='main':raise SystemExit('Upload requires main; exported parts remain available')
        paths=[p.resolve().relative_to(root).as_posix() for p in parts]
        if not paths:raise SystemExit('No HVP directions to upload')
        subprocess.run(['git','add','-f','--',*paths],cwd=root,check=True)
        subprocess.run(['git','commit','--only','-m','Upload exact step 4 HVP directions for audit','--',*paths],cwd=root,check=True)
        subprocess.run(['git','push','origin','main'],cwd=root,check=True)


if __name__=='__main__':main()
